name: Push handler

on:
  push:

concurrency:
  group: push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  firmware_pipeline:
    name: Build Firmware
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build_firmware.yml
    
